### ISSUE TITLE
ReactiveStreams interfaces should use smart pointers.

### ISSUE THREAD

**Issue by stupaq-fb** [ReactiveSocket/reactivesocket-cpp#11]

**Comment by stupaq-fb** [comment]
@yschimke You seems to be the most dedicated dog-food(-eat)er of this implementation. What do you think about this?

**Comment by yschimke** [comment]
I don't consider myself qualified to answer yet

**Comment by benjchristensen** [comment]
Based on my reading of the code, SmartPointers.d provides wrappers around `Subscriber` and `Subscription` that ensures certain behavior. That to me is not part of an "interface", but a concrete implementation.

I have had things like this such as [`SafeSubscriber`](https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/observers/SafeSubscriber.java), which enforce contractual behavior, that are very useful, but when they aren't needed, provide either overhead or undesired interference. 

So, why should `Subscriber` and `Subscription` interfaces have logic built into them, when they are interfaces?

I suggest interfaces should be left as interfaces without behavior, and implementing code can choose to use a common abstraction, which is exactly what we do here in ReactiveSocket with `SmartPionters.h`.

**Comment by stupaq-fb** [comment]
> that ensures certain behavior

It _accidentally_ ensures certain behaviour. What it does by design is that it ensures a unique ownership (try copying a smart pointer to a subscriber) that is checked at compile time, just like `std::unique_ptr`. This is precisely part of ReactiveStreams contract. Compare:
* `Subscriber::onSubscribe(Subscription&)`, which doesn't say anything about ownership by itself (you can complement it with a comment, but it would be nice to use the power of type system), with:
* `Subscriber::onSubscribe(SubscriptionPtr<Subscription>)`, which says precisely that the callee is given a unique ownership over the `Subscription` object pointed by the `SubscriptionPtr` and is expected to take care of delivering the terminal signal.

By using a smart pointers we make the compiler check ownership story for us, so we can just as well remove relevant comments about expected "ownership semantics", since it's encoded in the type system.

The pointers not only ensure unique ownership, but also prevent certain bugs. This part is a pure behaviour (e.g. delivering a terminal signal twice), but it's the same for `std::unique_ptr`, so I don't feel guilty for introducing this impurity.

**Comment by benjchristensen** [comment]
> This is precisely part of ReactiveStreams contract

It is part of the spec contract, but not what an interface needs to do. An implementation should concern itself with the contract. The interfaces are intended for interop between libraries that implement the interfaces. 

So I agree these should be used by implementations, but not part of the common interface that multiple implementations depend on.

**Comment by stupaq-fb** [comment]
I think we can only agree to disagree at this point. To me, who owns something is part of a contact, therefore, if type system allows for it, should be reflected in the interface.

**Comment by benjchristensen** [comment]
So your argument is that the definition of `Subscriber` is wrong?

**Comment by stupaq-fb** [comment]
Yes, I created the interface before I came up with smart pointers and no one put enough effort to use the new toy in the interface so far.

**Comment by benjchristensen** [comment]
Doesn't use of `SubscriptionPtr` just move the problem?

```c++
SubscriptionPtr<S> makeSubscriptionPtr(S* subscription) {
  return SubscriptionPtr<S>(subscription);
}
```

I will need to wrap a `Subscription`, and make sure to stop using that reference (or move it?). So how is that different that just ensuring I correctly move the Subscription into `onSubscribe`?

And what is the cost of requiring the extra wrapper every time?

My goal is that we extract the bare minimum interfaces that allow multiple libraries to interop, but leave a concrete implementation free to achieve the contract however they wish (and comply with the TCK that should eventually exist).

Having a concrete wrapper seems contrary to that.

**Comment by stupaq-fb** [comment]
The method you quoted is only there to make things less verbose in current version of C++, where template arguments of c'tors cannot be inferred (http://stackoverflow.com/questions/29677505/why-cant-constructors-deduce-template-arguments).

> I will need to wrap a Subscription, and make sure to stop using that reference (or move it?). So how is that different that just ensuring I correctly move the Subscription into onSubscribe?

I would say the point of making it a part of the interface is to encode the following sentence in the type system: "I, the caller of onSubscribe, render you, the callee, solely responsible for this Subscription". You can read it as the caller promising to behave as if it didn't retain any reference to the Subscription.

> And what is the cost of requiring the extra wrapper every time?

None. This abstraction, the way it looks like right now, has absolutely no cost at runtime unless you decide to use it's "RAII-style capabilities" (i.e. rely on d'tor sending a terminal signal).

> Having a concrete wrapper seems contrary to that.

We could have a wrapper that forbids copying and does nothing more and then another wrapper that delivers a terminal signal in a d'tor. Standard library went down the "more practical" (in my opinion) route and I followed it.

**Comment by lehecka** [comment]
To add a few points to the discussion here:
* expressing ownership in C++ class interface is very important and very useful. It came with C++11 and unique_ptrs and makes the contract clear. I can name bunch of frameworks which try to stay close to "bare pointers" and have open issues with memory management and cleanup (not mentioning exception cases).
* Smart pointers are used to improve productivity and I would say they are accepted in interfaces.
* On the other side I feel unsatisfied about SubscriptionPtr and SubscriberPtr as they try to look like smart pointers but they are not smart pointers. They don't have the semantic of a pointer and they also have hidden behavior (for cleanup, which I don't mind). For the C++ purists they will be quite confusing and problematic.

While I understand why do we use them in the code and why they are useful, I am not able to make the call yet. There are multiple other solutions to the problem and I didn't spend the time trying any of the other approaches. 
I think we should keep this issue open for a few weeks and gain more experience with the RS code as we write more client code on top of it.

**Comment by stupaq-fb** [comment]
Help me debug some buzz words.

> For the C++ purists they will be quite confusing and problematic.

Eeee... What is the "purist C++" you're referring to?

> but they are not smart pointers

I don't know the definition of a "smart pointer", but I thought it's a pointer that does something extra, i.e. frees something conditionally, prevents double freeing, etc.

> They don't have the semantic of a pointer and they 

They do have a pointer _semantics_. They don't have a _syntax_ of a pointer though. My proposal: just live with the fact you have to use a `.`, not `->`, we can rename them to SmartRefs but that'd be confusing as they are not references.

On pointer and reference _semantics_: https://isocpp.org/wiki/faq/references#refs-vs-ptrs and https://isocpp.org/wiki/faq/references#reseating-refs. So it really seems that the ability to change the object referred to is the only difference in semantics between a pointer and a reference. In this light, SubscriptionPtr and SubscriberPtr are semantically pointers.

**Comment by lehecka** [comment]
The main difference between smart pointers and Subscriber/SubscriptionPtr is that smart pointers provide overloaded operator-> which returns the raw pointer so by executing smart_pointer->foo(), you are executing the method of the pointed object. In our case we designed a wrapper class with methods and the user is calling the methods of this wrapper class, not the pointed object. I find this confusing for the user if we told them its a smart pointer class. I know the methods are called the same way and they should mimic the pointed object api. I think it would be cleaner and more understandable for other users if we show the true colors of the wrapper class and call it that way. With a proper name we can set the expectations of the user the right way.
I am not questioning the usefulness of the class, I think it's a useful one to have and I would find it useful if it is used in the framework API.

**Comment by stupaq-fb** [comment]
> The main difference between smart pointers and Subscriber/SubscriptionPtr is that smart pointers provide overloaded operator-> which returns the raw pointer so by executing smart_pointer->foo(), you are executing the method of the pointed object.

According to http://en.cppreference.com/w/cpp/memory/weak_ptr `weak_ptr` is a smart pointer. Please show me where it defines `operator->` or `operator*`.

**Comment by benjchristensen** [comment]
Doesn't the wrapper class also end up with the same problem itself? What guarantee is there that the code that created the wrapper class correctly moved ownership into the wrapper?

It seems that a unique_ptr with a custom deleter can give us what we need. Would that not suffice? That way instead of it being a custom wrapper class, it can just be a `std::unique_ptr<Subscription, Deleter>`.

**Comment by stupaq-fb** [comment]
> Doesn't the wrapper class also end up with the same problem itself? What guarantee is there that the code that created the wrapper class correctly moved ownership into the wrapper?

Nothing. Similarly you can construct two `unique_ptr`s pointing to the same object, is it an argument against using `unique_ptr` in an interface when you want to say that something is... well, a unique pointer to something else?

> It seems that a unique_ptr with a custom deleter can give us what we need. Would that not suffice? That way instead of it being a custom wrapper class, it can just be a std::unique_ptr<Subscription, Deleter>.

Not really:

std::unique_ptr<Subscriber, SubscriberDeleter> s = ...
s->onComplete();
s = foo(); // double free on s

Not to mention verbosity.

**Comment by lehecka** [comment]
This issue seems to be solved by the new memory model.
The API is returning/accepting shared_ptrs which will take care of the lifetime of the objects.
Since the lifetime of objects is no longer tight to terminating signals like onComplete or cancel, we don't have to protect the implementer from receiving multiple terminating signals.
The SubscriberPtr and subscriptionPtr wrappers bring nearly no value now and I will eventually remove them.
