### ISSUE TITLE
Configurable logging for LoggingMixin

### ISSUE THREAD

**Issue by maxwellsayles** [ReactiveSocket/reactivesocket-cpp#115]
I'm consuming ReactiveSockets in the ReactiveThrift framework.  The LoggingMixin is a bit noisy, and so I've commented out the logging locally so that I can see my log statements.  It would be great if this could be silent by default, and then the application could enable the ReactiveSockets logging, maybe through a `FLAG_reactivesocket_logging_enabled = true;`.

**Comment by yschimke** [comment]
Would VLOG(3) be more useful than LOG(INFO) instead?  Then it can be enabled per module during development.

For a server app, LOG(INFO) for anything per successful request is generally overkill.  You generally only want it writing logging for unexpected failures (not disconnects etc).

**Comment by maxwellsayles** [comment]
Yeah.  `VLOG(3)`  or even `VLOG(FLAG_reactivesocket_log_level)`  could work, and then the log level could be configured with a GFLAG.

**Comment by stupaq-fb** [comment]
I would use VLOG(6) for subscribe/unsubscribe events and VLOG(7) for request(n) and VLOG(8) for  onNext. Shifted arbitrarily. This is really low-level logging over here.

**Comment by lehecka** [comment]
obsolete. LoggingMixin doesn't exist anymore.
