### ISSUE TITLE
Separate compilation for each automaton

### ISSUE THREAD

**Issue by stupaq-fb** [ReactiveSocket/reactivesocket-cpp#12]
They are all instantiated in ReactiveSocket.cpp right now, I believe.

**Comment by lehecka** [comment]
what is your motivating factor? compile time? Or do we plan on using them separately?

**Comment by stupaq-fb** [comment]
More like a general refactoring how we instantiate automata. That'd inline all of the mixins in one function and save a bunch of kB of code, I suppose.

While doing it, I can also take care of not instantiating all templates in the same CU, so `-j` we pass to make actually does something.

**Comment by yschimke** [comment]
seems low enough priority we will never do this
