### ISSUE TITLE
Unnecessary check for COMPLETE flag in Frame_REQUEST_SUB/STREAM

### ISSUE THREAD

**Issue by Cristinag** [ReactiveSocket/reactivesocket-cpp#122]
Looking at SubscriptionResponderBase::onNextFrame(Frame_REQUEST_SUB&& frame) and StreamResponderBase::onNextFrame(Frame_REQUEST_STREAM&& frame), we’re checking if the Frame_REQUEST_SUB/STREAM frames received have the FrameFlags_COMPLETE flag set and if so we close  the connection. However according to the protocol these two frame types don’t use the COMPLETE flag, and it is also never set by Stream/SubscriptionRequester. 

Should these be removed?

**Comment by lehecka** [comment]
Verified with the protocol spec and you are right. Please, remove this functionality and send the PR.
