### ISSUE TITLE
folly (master) dependency on c++14

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket-cpp#123]
folly has been readded to brew.  I was able to install locally from source.

`brew install --build-from-source folly`

However the reactivesocket-cpp build fails because of a lot of errors, first one specifically mentions a C++14 dep.

```
/usr/local/include/folly/Synchronized.h:157:3: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
  auto withWLock(Function&& function) {
  ^
```

Editing CMakeLists.txt to use c++14 makes everything work again, but I believe we need c++11 support also.

**Comment by tmontgomery** [comment]
#129 is a stab at making the Mac happy for this.
