### ISSUE TITLE
OpenSSL on OSX

### ISSUE THREAD

**Issue by yschimke** [ReactiveSocket/reactivesocket-cpp#124]
I'm going to change the instructions for OSX development, but raising an issue for discussion.

I need to install openssl via brew and then run cmake like so

`OPENSSL_ROOT_DIR=/usr/local/opt/openssl cmake ../ -DCMAKE_BUILD_TYPE=DEBUG`

Is this the common experience?

**Comment by tmontgomery** [comment]
I use:

`$ cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl ..`
