### ISSUE TITLE
cancel() doesn't work with `SubscriberBase`

### ISSUE THREAD

**Issue by lexs** [ReactiveSocket/reactivesocket-cpp#175]
The cancel() impl in `SubscriptionShim` first checks and swaps cancelled to true but then checks again, expecting it to be false.

See https://github.com/ReactiveSocket/reactivesocket-cpp/blob/master/src/SubscriberBase.h#L57

**Comment by lehecka** [comment]
This is a good catch. Thank you. I will fix this today!

**Comment by lexs** [comment]
Fixed.
