### ISSUE TITLE
camelCase or underscore_

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveSocket/reactivesocket-cpp#318]
Working on new APIs, as well as Observable/Flowable, and ReactiveStreams ... question has been brought up whether we should use camelCase and capitalized class names, or if we should use the std and boost standards of everything being lower case and using underscores.

Current camelCase approach:

```cpp
    auto s = std::make_shared<ExampleSubscriber>(5, 6);
    rsf->connect().then([s](std::shared_ptr<RSocketRequester> rs) {
      rs->requestStream(Payload("Bob"), s);
    });
    s->awaitTerminalEvent();
```

or:

```cpp
    auto s = std::make_shared<example_subscriber>(5, 6);
    rsf->connect().then([s](std::shared_ptr<rsocket_requester> rs) {
      rs->request_stream(payload("Bob"), s);
    });
    s->await_terminal_event();
```

Current `Subscriber`:

```cpp
  void onSubscribe(std::shared_ptr<Subscription> subscription) noexcept override;
  void onNext(Payload element) noexcept override;
  void onComplete() noexcept override;
  void onError(folly::exception_wrapper ex) noexcept override;
```

or:

```cpp
  void on_subscribe(std::shared_ptr<subscription> subscription) noexcept override;
  void on_next(payload element) noexcept override;
  void on_complete() noexcept override;
  void on_error(folly::exception_wrapper ex) noexcept override;
```

**Comment by benjchristensen** [comment]
Note that I prefer camelCase ... but that's 20ish years of Java speaking. I do however find it easier to type camelCase than and underscore. 

folly uses camelCase: https://github.com/facebook/folly/tree/master/folly

Aeron C++ uses camelCase as well: https://github.com/real-logic/Aeron/tree/master/aeron-driver/src/main/cpp

**Comment by somasun** [comment]
camelCase++

**Comment by vjn** [comment]
std:: and boost:: are widely used; many libraries based off these (see, for instance "beast") follow the same conventions: lower_case_with_underscores. Programs using std::, boost:: and something else like folly:: have to inevitably deal with multiple styles everywhere. So, +1 for underscores.

**Comment by benjchristensen** [comment]
Further discussions inside FB leaned heavily towards camelCase. So ... camelCase.

**Comment by lehecka** [comment]
camelCase
