### ISSUE TITLE
rs-cpp doesn't set NEXT flag

### ISSUE THREAD

**Issue by lexs** [ReactiveSocket/reactivesocket-cpp#339]
Flag needs to be set here: https://phabricator.intern.facebook.com/diffusion/FBS/browse/master/fbcode/lithium/reactivesocket-cpp/src/ConnectionAutomaton.cpp;cb141271745a71b634844b724324464d8c1be345$845

rs-java errors out with "java.lang.IllegalArgumentException: Payload must set either or both of NEXT and COMPLETE.".

**Comment by mitermayer** [comment]
At whats stage does this happen, is it during initial connection ?

**Comment by lexs** [comment]
No, it happens after a `requestStream`.

**Comment by lehecka** [comment]
done
