### ISSUE TITLE
Allow destruction of ReactiveSocket instance from anywhere

### ISSUE THREAD

**Issue by stupaq-fb** [ReactiveSocket/reactivesocket-cpp#34]
...including any callbacks that are associated with the instance.

@yschimke @lehecka What should be the semantics over here?
1) Destroying ReactiveSocket kills all existing streams.
2) Destroying ReactiveSocket doesn't kill existing streams, but prevents any new streams from being accepted or requested.

**Comment by yschimke** [comment]
I don't have a strong opinion yet.  For me, its a synchronous or at least observable (Future?) operation that cleanly shuts down all streams and releases resources.  But I don't know that is agreed and may not make sense when invoked from a callback.

**Comment by stupaq-fb** [comment]
How about that. After destructor of ReactiveSocket finishes we guarantee:
* no new streams can be accepted,
* no new streams can be requested (trivial: ReactiveSocket instance is gone),
* all existing streams are closed and corresponding Subscriptions/Subscribers will _eventually_ receive terminal signals.

So it's not synchronous, but each Subscriber/Subscription on an open stream will learn about the failure as soon as possible. If we were to make d'tor synchronous, we'd likely deadlock if it's called from Subscriber/Subscription signal handler.

We don't need to cast the semantics in stone, but we should at least agree the v0 semantics of this operation "makes sense".

The reason things crash currently is simple: destroying ReactiveSocket instance from signal handler is not something I considered to be a valid behaviour. By an analogy to Thrift, destroying ThriftServer from RPC callback guarantees a crash/deadlock.

**Comment by yschimke** [comment]
That sounds like a reasonable plan to me.  I think we are just learning what makes sense as we go now, and that will keep evolving as we continue building and testing.

**Comment by stupaq-fb** [comment]
> I think we are just learning what makes sense as we go now, and that will keep evolving as we continue building and testing.

Absolutely agree. I just want us to know what to expect for now. We'll be able to expect a reasonable behaviour after a few iterations.
