### ISSUE TITLE
final folder structure

### ISSUE THREAD

**Issue by lehecka** [ReactiveSocket/reactivesocket-cpp#51]
We made some changes recently to the folder structure. We pulled reactive-streams-cpp to a separate repo, but kept the subfolder under reactivesocket-cpp. I believe it is just an obsolete artefact.
I want to understand the final folder structure. Here is my proposal:

reactive-streams-cpp (repo)
 * include
 * src 
   * utilities 
 * test
 * examples 
reactivesocket-cpp (repo)
 * src
   * automata
   * mixins
   * streams
 * test
 * cmake
 * devtools
 * externals
 * ...

The main difference between this proposal and the current state is essentially expanding reactive-streams-cpp/src to the root folder and moving reactivesocket-cpp/reactivesocket-cpp/src one level up.

Please let me know if there were any conversations about this which I missed.

**Comment by stupaq-fb** [comment]
> We pulled reactive-streams-cpp to a separate repo, but kept the subfolder under reactivesocket-cpp. I believe it is just an obsolete artefact.

I believe the reason folly, wangle, etc. use the same convention, is that you can then simply add a submodule with this library, include CMakeLists.txt and refer to header files with `reactivesocket-cpp/` prefix (i.e. the namespacing we thoroughly bikeshedded on in https://github.com/ReactiveSocket/reactivesocket-cpp/pull/48). There are probably other ways of achieving this.

Other than that, I believe there are a few levels of indentation missing.

Also, we can't make reactive-streams-cpp depend on reactivesocket-cpp (as a submodule or in any other form), as the latter depends on he former.

**Comment by yschimke** [comment]
I believe this is closed, we have a structure I think we are happy with
