### ISSUE TITLE
Align reactive-streams-cpp classnames with Java

### ISSUE THREAD

**Issue by robertroeser** [ReactiveSocket/reactivesocket-cpp#9]
ReactiveStreams C++ version has different class names than the Java version. For instance a instead of a Publisher it has a Producer. Maybe I'm wrong but it seems like the C++ version should flow the naming convention in the Java implementation so it's easier to follow between them. The Processor class is missing as well.

**Comment by stupaq-fb** [comment]
Renaming Producer/Publisher to match JVM version sounds like a good idea.

What is the added value of Processor? I can't see it after reading https://github.com/reactive-streams/reactive-streams-jvm/tree/v1.0.0#4processor-code, i.e. I don't see additional restrictions on top of a union of restrictions imposed by Subscriber and Subscription. Unless I'm missing something, I would prefer "not to multiply entities unnecessarily".

Also, I haven't thought about it too much, but what would be the definition of the interface? Does it make sense to use virtual/non-virtual inheritance for any of Subscriber/Subscription? Maybe both? Unless we come up with strong reasoning behind any of the options to "merge" two interfaces into one, I would prefer to leave that decision to the user.

**Comment by robertroeser** [comment]
You can use it as proxy between a subscriber and a publisher. Something external to the Publisher can send items it re-emits to down stream subscribers, of which could have multiple. 

A Subject in RxJava is analogous, and provides useful examples of what you can implement with a Processor.

**Comment by stupaq-fb** [comment]
Does the Processor carry any additional semantics on top of Subscriber and Subscription? Based on the spec, it looks to me that anything that implements both interfaces meets the rules, hence the interface doesn't add any more information, doesn't tell anything more than the fact that both interfaces are implemented.

To better state my question: can I always turn a class that implements both Subscription and Subscriber into a class which implements a Processor? If yes, then why does the class exist (maybe it's some artefact of the type system)?

> You can use it as proxy between a subscriber and a publisher. Something external to the Publisher can send items it re-emits to down stream subscribers, of which could have multiple.

Isn't it true about anything that implements both interfaces? Are there any restrictions on what sort of operations a processor can perform?

The question about virtual/non-virtual inheritance remains. I am not yet sure what makes sense here. Unless we have a use case to confirm, I am not comfortable making the decision.

**Comment by robertroeser** [comment]
The Processor is a Subscriber and a Publisher because you can't describe to a subscription. It's part of the ReactiveStreams protocol. A Processor is both a Subscriber or a Publisher, not a Subscription. A Processor has specific behaviors that it must implement to be compliant that are different than a Subscriber or Publisher by it self. It's in the ReactiveStreams protocol definition so to implement it you need to implement a Processor. This is an implementation of the protocol?

**Comment by stupaq-fb** [comment]
Oh, sorry, I was thinking about Publisher and kept writing about Subscription. Sorry for the confusion. I did mean Publisher in each and every of my comments above.

> A Processor has specific behaviors that it must implement to be compliant that are different than a Subscriber or Publisher by it self.

Good, we can add it then, together with an example of a a class that is both Subscriber and Publisher but does not obey the rules for Processor.

> It's in the ReactiveStreams protocol definition so to implement it you need to implement a Processor. This is an implementation of the protocol?

The reactive-streams-cpp aims at defining a ReactiveStreams spec for C++ that is in-line with http://www.reactive-streams.org/. There are and will be differences between this spec and the spec for JVM, because different languages mean different problems and points of focus.

**Comment by yschimke** [comment]
@robertroeser Is a Processor any valid component that implements both?  Semantically does it apply to a service that I can send requests to and read responses?  But not to a Filter that subscribes and re-publishes some of the elements.

**Comment by yschimke** [comment]
n.b. Producer/Publisher is already aligned now on Publisher

**Comment by yschimke** [comment]
This seems low priority, if we want processor specifically let's open an issue for that. Publisher was already fixed.
